spring:
  datasource:
    url: jdbc:postgresql://localhost:62866/ShortLinkDb
    username: user
    password: 7757
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
